spring.application.name=notification-service

server.port=8082

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=DB12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ==========================================
# EMAIL SMTP CONFIGURATION
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Replace with your Gmail address
spring.mail.username=yourgmail@gmail.com

# Replace with your Gmail App Password
spring.mail.password=your_16_digit_app_password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional Debug Logging
spring.mail.properties.mail.debug=true