spring.application.name=booking-service

# Server Configuration
server.port=8083
server.servlet.context-path=/api/service-requests

# Debug
debug=true

# Spring Cloud
spring.cloud.compatibility-verifier.enabled=false

# Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=c##request_schema
spring.datasource.password=request1123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Logging
logging.level.com.hsms.booking=DEBUG