spring.application.name=payment-service

server.port=8081

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=c##myuser1
spring.datasource.password=myuser123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
