spring.application.name=category-service

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=c##myuser
spring.datasource.password=myuser123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cloud.config.import-check.enabled=false