spring.application.name=analytics-service

server.port = 8084
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=c##analytics_schema
spring.datasource.password=analytics123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
